data_source test_data:
     type: snowflake
     username:  ${SNOWFLAKE_USERNAME}
     password:  ${SNOWFLAKE_PASSWORD}
     account: xd44007.ap-southeast-1
     database: Test
     schema: Test_Schema
     warehouse: compute_wh
     role: ACCOUNTADMIN
     
soda_cloud:
     host: cloud.soda.io
     api_key_id: ${SODA_CLOUD_API_KEY}
     api_key_secret: ${SODA_CLOUD_API_SECRET}
     
