data_source test_data:
     type: snowflake
     username: Vaishnavi1
     password: Snowflake@123
     account: me82430.central-india.azure
     database: Client_db
     schema: Client_db_Schema
     warehouse: compute_wh
     role: ACCOUNTADMIN
     
soda_cloud:
     host: cloud.soda.io
     api_key_id: a0cf5175-ed8e-4fba-a665-6481217aec80
     api_key_secret: 5ZrYXqRZFBptAmb7wVMbHVBRTiprgLzqd0XfqAVKVlYWLjUB2Zc8DQ
