data_source TestData:
     type: snowflake
     username: ${ SNOWFLAKE_USERNAME }
     password: ${ SNOWFLAKE_PASSWORD }
     database: Test
     schema: Test_Schema
     warehouse: compute_wh
     role: ACCOUNTADMIN

      
   soda_cloud:
     host: cloud.us.soda.io
     api_key_id: ${ SODA_API_KEY }
     api_key_secret: ${ SODA_CLOUD_API_SECRET } 
