data_source test_data:
     type: snowflake
     username: Deepti11
     password: Snowflake@1$11
     account: XC41408
     database: Test
     schema: Test_Schema
     warehouse: compute_wh
     connection_timeout: 240
     role: ACCOUNTADMIN
soda_cloud:
     host: cloud.soda.io
     api_key_id: 0c69895e-7acb-4f8f-a58a-e897ca7a1922
     api_key_secret: LU1H2Yu1FKpXAR8Fhatcoi_0ZatKbA-WyAO7Okpk6ny7w6VYr_g6LQ 
     scheme: https
