  
name: Scan for data quality
on:
  pull_request:
    branches:
      - main  # Adjust the branch name as needed
  push:
    branches:
      - main 
jobs:
  soda_scan:
    runs-on: ubuntu-latest
    name: Run Soda Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Soda Library Action
        uses: sodadata/soda-github-action@v1.0.2
        with:
         soda_library_version: v1.0.4
         data_source: test_data
         configuration: ./Soda/configuration.yml
         checks: ./Soda/checks.yml


      - name: Perform Soda Scan
        uses: sodadata/soda-github-action@v1.0.2
        env:
         SODA_CLOUD_API_KEY: 1942e95c-25c5-415c-b369-01be79d16ba4
         SODA_CLOUD_API_SECRET: r9T0iizPHKndz0rReBNAsAHCKV0SN7clPUE3l4TY0ddomZfcKl8bzw
         SNOWFLAKE_USERNAME: Deepti11
         SNOWFLAKE_PASSWORD: Snowflake@1$11
        with:
          soda_library_version: v1.0.4
          data_source: snowflake
          configuration: ./Soda/configuration.yml
          checks: ./Soda/checks.yml
              

