  
name: Scan for data quality
on:
  pull_request:
    branches:
      - main  # Adjust the branch name as needed
  push:
    branches:
      - main 
jobs:
  soda_scan:
    runs-on: ubuntu-latest
    name: Run Soda Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Soda Library Action
        uses: sodadata/soda-github-action@v1.0.2
        with:
         soda_library_version: v1.0.4
         data_source: test_data
         configuration: ./Soda/configuration.yml
         checks: ./Soda/checks.yml


      - name: Perform Soda Scan
        uses: sodadata/soda-github-action@v1.0.2
        env:
         SODA_CLOUD_API_KEY: 0c69895e-7acb-4f8f-a58a-e897ca7a1922
         SODA_CLOUD_API_SECRET: LU1H2Yu1FKpXAR8Fhatcoi_0ZatKbA-WyAO7Okpk6ny7w6VYr_g6LQ
         SNOWFLAKE_USERNAME: Deepti11
         SNOWFLAKE_PASSWORD: Snowflake@1$11
        with:
         soda_library_version: v1.0.4
         configuration: ./Soda/configuration.yml
         checks: ./Soda/checks.yml
        
              

